env:
  global:
    - CC_TEST_REPORTER_ID=9df7f23b03b295bd949e282b01465157664a32d6f50f742160ed42baa091095f
language: node_js
node_js:
  - 12
before_install:
  - npm install -g webpack
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-with-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
